2024-12-02 04:57:31 [ERROR] The user could not be deleted d794a5d3-8001-4d4d-8f7a-f341e396451c: Request failed with status 404
Traceback (most recent call last):
  File "/home/runner/work/qa-hackathon-raptors/qa-hackathon-raptors/conftest.py", line 70, in new_user
    user_api_client.delete_user(str(user["uuid"]), task_id)
  File "/home/runner/work/qa-hackathon-raptors/qa-hackathon-raptors/services/users/user_api_client.py", line 70, in delete_user
    raise ValueError(msg)
ValueError: Request failed with status 404
