DEBUG    asyncio:selector_events.py:64 Using selector: EpollSelector
ERROR    root:conftest.py:73 The user could not be deleted 2486e04f-45fd-46cb-b214-e341495d7cfa: Request failed with status 404
Traceback (most recent call last):
  File "/home/runner/work/qa-hackathon-raptors/qa-hackathon-raptors/conftest.py", line 70, in new_user
    user_api_client.delete_user(str(user["uuid"]), task_id)
  File "/home/runner/work/qa-hackathon-raptors/qa-hackathon-raptors/services/users/user_api_client.py", line 70, in delete_user
    raise ValueError(msg)
ValueError: Request failed with status 404